# Generated by Django 6.0.5 on 2026-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('client', 'Клієнт'), ('manager', 'Менеджер'), ('admin', 'Адміністратор')], default='client', help_text='Роль пользователя определяет уровень доступа в системе', max_length=10, verbose_name='Роль'),
        ),
    ]
