# Generated by Django 6.0.5 on 2026-05-21 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_customuser_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='saved_cart',
            field=models.JSONField(blank=True, default=dict, help_text='Кошик зберігається автоматично при виході з системи', verbose_name='Збережений кошик'),
        ),
    ]
