# Generated by Django 6.0.5 on 2026-05-21 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='status',
            field=models.CharField(choices=[('new', 'Нова'), ('received', 'Отримана'), ('cancelled', 'Скасована')], default='new', max_length=15, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='supplyitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, help_text='Цена за единицу товара у поставщика', max_digits=10, verbose_name='Закупочная цена (₴)'),
        ),
    ]
