# Generated by Django 6.0.5 on 2026-05-21 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price'),
        ('warehouse', '0002_alter_supply_status_alter_supplyitem_purchase_price'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stock_quantity_non_negative'),
        ),
    ]
