# Generated by Django 6.0.5 on 2026-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='specs',
            field=models.JSONField(blank=True, default=dict, help_text='Словник "назва": "значення", наприклад: {"Дисплей": "6.1 OLED"}', verbose_name='Характеристики'),
        ),
    ]
